name: CI
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  schedule:
    # once a week at midnight on Sunday
    - cron: "0 0 * * 0"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true
  
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3

    - id: get-last-python
      uses: ./
      with:
        last-n-minor-release: 0

    - id: get-last-1-python
      uses: ./
      with:
        last-n-minor-release: 1
    
    - id: get-last-2-python
      uses: ./
      with:
        last-n-minor-release: 2
    
    - name: Check version
      shell: bash
      run: |
        [[ "${{ steps.get-last-python.outputs.python-version }}" == "3.11" ]] || exit 1
        [[ "${{ steps.get-last-1-python.outputs.python-version }}" == "3.10" ]] || exit 1
        [[ "${{ steps.get-last-2-python.outputs.python-version }}" == "3.9" ]] || exit 1
